/*

JS meta-language review

[JS meta]
----

----

*/ 

let lib = require('./functions.JS');

function Main() {
    
    // variable
    lib.VariableDmo()
    // funtion
    lib.FunctionDemo()
    // statement
    lib.StatementDemo()
    // control flow
    lib.ControlflowDemo()
    // loop
    lib.LoopDemo()
    // class
    lib.ClassDemo()
    // container
    lib.ContainerDemo()

    // DOM

}